package LSHFIndex;
import global.Vector100Dtype;
import heap.Heapfile;

import java.util.Map;

/**
 * A layer is a collection of " n = num_hash_functions" unique hash functions (h_1...h_n)
 * h1,h2,h3 ... form a layer together.
 * a hash is generated by a layer after
 * evaluating an input on all the hash functions in the layer.
 * num_hash_functions - hashes per layer
 * hashFunctions - array of hashfunctions
 * layer_map - a map that maps generated hash to its corresponding heapfile
 *
 */
public class Layer
{
    int num_hash_functions;
    HashFunction[] hashFunctions;
    Map<Integer[], Heapfile>  layer_map;

    public Layer(int h, int bin_length)
    {
        this.num_hash_functions = h;
        hashFunctions = new HashFunction[num_hash_functions];
        for (int i = 0; i < num_hash_functions; i++)
        {
            hashFunctions[i] = new HashFunction(bin_length);
        }
    }

    // Layer hash is an array of integers.
    // this array will be converted to strings when necessary for storing heapfile name
    // We want to keep the hash as an array of integers instead of
    // one integer or one string to avoid the following situation:
    // Suppose we have 2 hash functions h1 and h2
    // for 2 different inputs i1 and i2, suppose we get
    // h1(i1) = 32  h2(i1) = 3
    // h1(i2) = 3   h2(i2) = 23
    // if we use single string/int which is a concatenation of h1 and h2,
    // both the inputs will end up having the same hash 323. We do not want this.

    public int[] layer_hash(Vector100Dtype input)
    {
        int[] layer_hash = new int[num_hash_functions];
        int hash = 0;
        for (int i = 0; i < num_hash_functions; i++)
        {
            layer_hash[i] = hashFunctions[i].hash(input);
        }
        return layer_hash;
    }


}
